"""Bundle builder — one upload artifact per Colab session (FTT-20 prep).

`abliterate bundle --spec <yaml>` emits a self-contained tarball:
package source + pyproject + uv.lock + the run spec + runner.sh +
bundle_meta.json (per-file hashes for pull-back verification).

Contract (agreed with the Colab operator, 2026-09-29):
- runner installs with `uv sync --frozen` (exact versions CI validated),
  inside a --system-site-packages venv so Colab's preinstalled CUDA
  torch/transformers are used instead of a duplicate download;
- sentinel contract stays engine-owned: /content/exit_code.txt,
  stdout ENG<STAGE>_DONE {json}, <stage>_error.txt per out dir;
- ENG_OUT_ROOT defaults to /content and the engine derives the per-run
  directory itself (eng_run_<NNN>_<patient>) so no two runs share a dir.
"""
import hashlib
import json
import os
import shutil
import subprocess
import tarfile
import tempfile
from pathlib import Path

from . import __version__
from .spec import load_spec, spec_hash

RUNNER_TEMPLATE = r"""#!/usr/bin/env bash
# Generated by `abliterate bundle` (abliteration_engine {version}) —
# do not edit by hand; regenerate from the spec instead.
set -euo pipefail
BUNDLE_DIR="$(cd "$(dirname "$0")" && pwd)"
PHASE="${{PHASE:-run}}"          # run | ladder | mmlu | publish (FTT-20 verbs)
SPEC="{spec_name}"

echo "[bundle] phase=$PHASE spec=$SPEC"

# uv on Colab (pip lands it in the system env; uv itself drives the venv)
if ! command -v uv >/dev/null 2>&1; then
  pip install -q uv
fi

cd "$BUNDLE_DIR"
# --system-site-packages: use Colab's preinstalled CUDA torch/transformers;
# uv sync --frozen: install the package + wheel deps exactly as CI validated.
uv venv --system-site-packages --python "$(command -v python3)" .venv
uv sync --frozen

# Engine derives/creates $ENG_OUT_ROOT/eng_run_<NNN>_<patient> itself;
# sentinels stay engine-owned (abliteration_engine/core.py), no runner-side
# sentinel writes — the poll loop contract is unchanged.
export ENG_OUT_ROOT="${{ENG_OUT_ROOT:-/content}}"

exec "$BUNDLE_DIR/.venv/bin/abliterate" "$PHASE" \
  --spec "$BUNDLE_DIR/specs/$SPEC" --i-know-this-spends-quota
"""


def _sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _git_commit(repo_dir):
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=repo_dir,
                              capture_output=True, text=True, timeout=10
                              ).stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def build_bundle(spec_path, out_dir="bundles", repo_root=None):
    """Build the bundle tarball for a run spec. Returns artifact paths."""
    repo_root = repo_root or _find_repo_root()
    lock_path = os.path.join(repo_root, "uv.lock")
    pyproject = os.path.join(repo_root, "pyproject.toml")
    src_dir = os.path.join(repo_root, "src", "abliteration_engine")
    for p in (lock_path, pyproject, src_dir):
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"bundle needs {p} — run from a checked-out repo with uv.lock")
    spec = load_spec(spec_path)  # full fail-fast validation of the spec
    rc = spec["run_card"]
    name = f"eng_run_{rc['run_number']:03d}_{rc['patient']}"
    spec_name = os.path.basename(spec_path)

    stamp = subprocess.run(
        ["date", "-u", "+%Y%m%dT%H%M%SZ"], capture_output=True,
        text=True, timeout=10).stdout.strip()
    tmp = tempfile.mkdtemp(prefix=f"{name}_")
    try:
        staging = os.path.join(tmp, name)
        shutil.copytree(src_dir, os.path.join(staging, "src",
                                              "abliteration_engine"),
                        ignore=shutil.ignore_patterns("__pycache__"))
        os.makedirs(os.path.join(staging, "specs"), exist_ok=True)
        shutil.copy2(spec_path, os.path.join(staging, "specs", spec_name))
        shutil.copy2(pyproject, os.path.join(staging, "pyproject.toml"))
        shutil.copy2(lock_path, os.path.join(staging, "uv.lock"))
        # pyproject declares readme = "README.md"; the wheel build reads it,
        # so the bundle must carry it (caught live on Colab 2026-09-30:
        # uv sync failed 'failed to open /content/parity/README.md')
        readme_src = os.path.join(repo_root, "README.md")
        if os.path.exists(readme_src):
            shutil.copy2(readme_src,
                         os.path.join(staging, "README.md"))

        runner = RUNNER_TEMPLATE.format(version=__version__,
                                        spec_name=spec_name)
        with open(os.path.join(staging, "runner.sh"), "w") as f:
            f.write(runner)
        os.chmod(os.path.join(staging, "runner.sh"), 0o755)

        manifest = {
            "spec_name": spec_name,
            "spec_sha256": spec_hash(spec),
            "engine_version": __version__,
            "source_git_commit": _git_commit(repo_root),
            "uv_lock_sha256": _sha256_file(lock_path),
            "run_dir": name,
            "eng_out_dir": f"eng_run_{rc['run_number']:03d}_"
                           f"{rc['patient']}",
        }
        files = {}
        for root, _, fns in os.walk(staging):
            for fn in sorted(fns):
                p = os.path.join(root, fn)
                files[os.path.relpath(p, staging)] = _sha256_file(p)
        manifest["files"] = files
        with open(os.path.join(staging, "bundle_meta.json"), "w") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)

        os.makedirs(out_dir, exist_ok=True)
        tar_path = os.path.join(out_dir, f"{name}_{stamp}.tar.gz")
        with tarfile.open(tar_path, "w:gz") as tf:
            for rel in sorted(os.listdir(staging)):
                tf.add(os.path.join(staging, rel), arcname=rel)
        sha = _sha256_file(tar_path)
        with open(tar_path + ".sha256", "w") as f:
            f.write(sha + "  " + os.path.basename(tar_path) + "\n")
        return {"tar": os.path.abspath(tar_path),
                "sha256": sha, "run_dir": name, "spec_sha": spec_hash(spec)}
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _find_repo_root():
    """Locate repo root: walk up from CWD for pyproject.toml."""
    p = Path.cwd()
    while p != p.parent:
        if (p / "pyproject.toml").exists() and (p / "uv.lock").exists():
            return str(p)
        p = p.parent
    raise FileNotFoundError(
        "repo root (pyproject.toml + uv.lock) not found from CWD; pass "
        "--bundle-repo-root or run from inside the repo")