"""`abliterate init --model <hf id>` — write a starter run spec.

The two things beginners get stuck on when writing a spec by hand are
resolved from the Hugging Face hub here:
- patient.revision: the branch/tag/sha asked for (default main) is resolved
  to its full 40-char commit sha (the pin load_spec demands);
- patient.structure_expect: filled from the pinned config.json, so stage 1's
  shape check matches the real model.

Also reports, before any GPU time, whether the architecture is one the
engine's edits are known to fit and whether the tokenizer ships a chat
template. CPU-only; needs network + huggingface_hub (a transformers dep).
"""
import json
import os
import re
import sys

from .spec import SpecError, load_spec

# decoder layout the engine edits: model.model.layers[i].self_attn.o_proj,
# .mlp.down_proj, model.model.norm (RMSNorm w * x_hat)
TESTED_MODEL_TYPES = {"qwen2"}
SAME_LAYOUT_UNTESTED = {"llama", "mistral", "qwen3"}

_TEMPLATE = """\
# Generated by `abliterate init --model {model_id}` — edit freely, then:
#   abliterate validate --spec {spec_path}
#   abliterate plan --spec {spec_path}
spec_version: 1
run_card:
  run_number: {run_number}
  patient: {patient}
  purpose: "first abliteration run of {model_id}"

patient:
  model_id: {model_id}
  revision: "{sha}"   # pinned from '{ref}'
  structure_expect:   # from the pinned config.json; stage 1 asserts these
{structure}
probe_sets:
  harmful: builtin:primary64_harmful
  harmless: builtin:primary64_harmless
  n_pairs: 64
  n_probes: 16          # raise to 64 for tighter percentages (4x probe time)
  refusal_markers: builtin:fp_explicit_v1

decoding:
  max_new_tokens: 200
  strategy: greedy
  seed: 0

ladder:
  variants: [wd_B, wd_BN, wd_ML, wd_ML_BN]   # [] = measure only, no edits
  k_primary: 3
  k_combo: 5

gates:
  benign_floor_delta: 0.10
  degenerate_max: 0
  publish_refusal: 0.25
  mmlu_max_loss_pp: 3.0

publish:
  repo_id: {repo_id}
  license: {license}
  card_marker: "abliterated with abliteration_engine"
  verify_disk_bounds:
    lm_head: 0.005
    final_norm: 0.05
    layer_row: 0.01

hitl:
  after_selection: true
  before_publish: true
"""


def _slug(model_id):
    return re.sub(r"[^a-z0-9.]+", "-", model_id.split("/")[-1].lower()).strip("-")


def structure_from_config(cfg):
    """structure_expect keys derivable from config.json alone. Keys whose
    value the config does not state (and transformers would default per
    architecture) are left out rather than guessed."""
    out = {}
    if "num_hidden_layers" in cfg:
        out["num_hidden_layers"] = cfg["num_hidden_layers"]
    if "num_attention_heads" in cfg:
        out["num_attention_heads"] = cfg["num_attention_heads"]
    if "num_key_value_heads" in cfg:
        out["num_key_value_heads"] = cfg["num_key_value_heads"]
    if "tie_word_embeddings" in cfg:
        out["tie_word_embeddings"] = bool(cfg["tie_word_embeddings"])
    h, n_heads = cfg.get("hidden_size"), cfg.get("num_attention_heads")
    if h and n_heads:
        head_dim = cfg.get("head_dim") or h // n_heads
        out["o_proj_shape"] = [h, n_heads * head_dim]
    if h and cfg.get("intermediate_size"):
        out["down_proj_shape"] = [h, cfg["intermediate_size"]]
    return out


def _yaml_structure(struct):
    lines = []
    for k, v in struct.items():
        val = str(v).lower() if isinstance(v, bool) else v
        lines.append(f"    {k}: {val}")
    return "\n".join(lines) + "\n"


def architecture_verdict(cfg):
    """(level, message): level in ok / warn / unsupported."""
    mt = cfg.get("model_type", "?")
    if mt in TESTED_MODEL_TYPES:
        return "ok", f"architecture '{mt}': tested with this engine"
    if mt in SAME_LAYOUT_UNTESTED:
        return "warn", (f"architecture '{mt}': same module layout as the "
                        "tested Qwen2 family, but not yet run end-to-end — "
                        "treat the first run as an experiment")
    return "unsupported", (
        f"architecture '{mt}' is not one the engine's weight edits are known "
        "to fit (needs model.layers[i].self_attn.o_proj / .mlp.down_proj and "
        "an RMSNorm final norm). Stage 1 checks the real module layout and "
        "will stop before any heavy GPU work if it does not match.")


def init_spec(model_id, revision=None, out=None, run_number=1,
              patient_name=None, api=None, download=None):
    """Write the starter spec; returns a CLI exit code."""
    try:
        if api is None or download is None:
            from huggingface_hub import HfApi, hf_hub_download
            api = api or HfApi()
            download = download or hf_hub_download
    except ImportError:
        print("REFUSING: init needs huggingface_hub "
              "(pip install huggingface_hub)", file=sys.stderr)
        return 2

    ref = revision or "main"
    try:
        info = api.model_info(model_id, revision=ref)
    except Exception as e:  # repo missing / gated / offline
        print(f"REFUSING: could not read {model_id}@{ref} from the hub — "
              f"{type(e).__name__}: {e}", file=sys.stderr)
        return 2
    sha = info.sha
    files = {s.rfilename for s in (info.siblings or [])}
    cfg = json.load(open(download(model_id, "config.json", revision=sha)))

    level, msg = architecture_verdict(cfg)
    print(f"{'OK' if level == 'ok' else 'WARNING'}: {msg}")
    has_template = "chat_template.jinja" in files
    if not has_template and "tokenizer_config.json" in files:
        tc = json.load(open(download(model_id, "tokenizer_config.json",
                                     revision=sha)))
        has_template = bool(tc.get("chat_template"))
    if not has_template:
        print("WARNING: no chat template found — the engine wraps every "
              "prompt with the tokenizer's chat template; use the model's "
              "-Instruct/-Chat variant")

    patient = patient_name or _slug(model_id)
    if out is None:
        d = "specs" if os.path.isdir("specs") else "."
        out = os.path.join(d, f"{patient}.yaml")
    if os.path.exists(out):
        print(f"REFUSING: {out} exists — pass --out to choose another path",
              file=sys.stderr)
        return 2

    repo_id = "null   # set to <your-hf-name>/<model>-abliterated to publish"
    try:
        who = api.whoami()["name"]
        repo_id = f"{who}/{model_id.split('/')[-1]}-abliterated"
    except Exception:
        pass  # not logged in: publish stays gated off until set
    card = getattr(info, "card_data", None)  # CardData or dict; both .get
    license_ = (card.get("license") if hasattr(card, "get") else None) \
        or "apache-2.0"

    text = _TEMPLATE.format(model_id=model_id, spec_path=out,
                            run_number=int(run_number), patient=patient,
                            sha=sha, ref=ref,
                            structure=_yaml_structure(
                                structure_from_config(cfg)),
                            repo_id=repo_id, license=license_)
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write(text)
    try:
        load_spec(out)
    except SpecError as e:  # should not happen; surface rather than hide
        print(f"WARNING: generated spec does not validate: {e}",
              file=sys.stderr)
        return 1
    print(f"wrote {out}  ({model_id} @ {sha[:12]})")
    print(f"next: abliterate plan --spec {out}")
    return 0
